on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: [self-hosted, ARM64]
    steps:

      - uses: actions/checkout@v2
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME}}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        env:
          project: ugly-portfolio
        run: |
          docker build -t port-app-${{ github.run_id }} .
          docker tag port-app-${{ github.run_id }} ${{ secrets.DOCKERHUB_USERNAME}}/${project}:0.${{ github.run_number }}.${{ github.run_attempt }}
          docker push ${{ secrets.DOCKERHUB_USERNAME}}/${project}:0.${{ github.run_number }}.${{ github.run_attempt }}